### ISSUE TITLE
fist time startup app looks broken !!!

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#10]
wyen you log into v3 for the first time the app looks broken - i assue this will also be what first time users see ?

we need a dialog popup saying 'Syncing with the Senit Databse' or something here so people dont freak out..

mayte freaked out when she saw the attached image and it took a good 20 seconds to sync up this is not good guys. i would also hide the 0 btc wallet amount! it will freak people out if this happens again in the future.

![image from ios 4](https://user-images.githubusercontent.com/6324793/43374847-10925726-93b2-11e8-9719-73b52ca73545.jpg)

**Comment by Ibar000** [comment]
completed
