### ISSUE TITLE
chat to be like whatsapp

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#100]
the chat needs to be just like whatsapp! when in doubt compare them

1. need check and double check to see when a message is delivered vs sent
2. larger fonts and pale blue background behind chats
3. same style main chat screen, with latest chat popping to the top always

its not hard to compare them and match the functionality - whats app done it right we dont need to reinvent the wheel here

**Comment by jayrulez** [comment]
Superseded by #167
