### ISSUE TITLE
profile page - address

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#104]
address is missing from the profile page ? user needs a way to enter their address (like any standard online address form) as well as a way to submit and upload proof of address so we can verify it

**Comment by jayrulez** [comment]
Server side module is in place for this.

@jovi959 @Ibar000 let me know if you need any extra info implementing this.

**Comment by jayrulez** [comment]
@tajwane

**Comment by jahshaka** [comment]
is this now a duplicate of

https://github.com/SenitCorp/bugtracker/issues/164

can we get rid of one of these
