### ISSUE TITLE
terms of use and privacy policy

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#105]
we need to split terms of use into 

terms of use
privacy police

we can copy the terms of use in the provacy policy to start and then have administartion give us seperate data for each page....

you see this when signing up - it also needs to be accessable via the settings section for users to review

**Comment by Ibar000** [comment]
Karsten,
Do you therefore want "Legal" (which is on the Settings page) to be split into "Terms of use" and "Privacy policy"?

**Comment by jovi959** [comment]
Android completed

**Comment by jayrulez** [comment]
@jovi959 how about iOS? can we close this?

**Comment by jovi959** [comment]
iOS Completed
