### ISSUE TITLE
cant see people in address book

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#11]
when you search for users in phone book in the address book the sort is wrong should be alphabetial  start to finsin not sorted inside words...

and also users are hidden under the text popup need a way to address this as most people think favourates dont show up in the address book search and the should (ie they shgould not be listed at the bottom as they are) and we need a clear way to show the scroll bar so users know to scroll

**Comment by jovi959** [comment]
iOS drop keyboard when person begins to scroll so they can see all contacts
