### ISSUE TITLE
email address on send request pages - friends vs not friends

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#112]
need to make sure we have privacy on send request pages when the person is not a contact - currently it shows the email address for a contact thats not a verified contact

so like friends vs friend of a friend or nota friend  - they become a friend once you have sent them funds - we need to discuss this as we dont want people scraping email addresses

need tis concept in our data base - frinds vs strangers

if they are a freind you can view all data if they are not you see name and number only

what we dont want is 👍 

1 send a phone number a request for funds and tehn get all their contact data even tough they are not a contact

**Comment by jayrulez** [comment]
Does this mean that we have changed the decision to just remove email addresses for those pages completey?

**Comment by jahshaka** [comment]
we want to remove them by default for sure its a security issue... but this goes both ways especially if you have two people with the same name..

so implelent the following rules:

if you have done

1 successful 2 way transaction with another user 
both users are email verified 

then show it on their ADDRESS BOOK page only...

ALSO

i think if a user is REQUESTING FUNDS and are EMAIL VERIFIED 

show it on the request for funds page... on the receipt would be good both pre approval and pist approval

KArsten

**Comment by jayrulez** [comment]
Basically the same as issue #162 
Closing this one.
