### ISSUE TITLE
bitcoin transaction status different from receipt

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#114]
when you send someone bitcoin and the transaction is 'sending / receiving' 

on my side its 'receiving' as in waiting on confirmations

the receipt header says 

Received from Bitcoin Address

but it should be 

Receiving from Bitcoin address

until its confirmed and received...

and the bitcoin address is not listed on the receipt it should be ??? dont we know where its coming from ???

**Comment by jayrulez** [comment]
We can use heuristics to guess where it is coming from. In most cases we will know.

It doesn't necessarily come from one input.

**Comment by jayrulez** [comment]
bump

**Comment by jayrulez** [comment]
bump.

An output can come from 1 or more input.

That means for any bitcoin transaction, the value received can come from 1 or more addresses. We cannot say a transaction comes from a single address in some cases.

For bitcoin transactions it makes no sense to "sender" or it is coming from a particular address.

Persons interested in that stuff can view the transaction on the block explorer if they really want to see the inputs and outputs.

**Comment by jahshaka** [comment]
ok got it so you can close that side out then, if we dont know where its coming from and its a external send then so be it

but can we fix teh formatting of the text for the users...

ie

when you send someone bitcoin and the transaction is 'sending / receiving'

on my side its 'receiving' as in waiting on confirmations

the receipt header says

Received from Bitcoin Address

but it should be

Receiving from Bitcoin address

**Comment by SamuelFolkes** [comment]
bump @jovi959 @Ibar000

**Comment by jovi959** [comment]
iOS Completed

**Comment by Ibar000** [comment]
fixed on Android
