### ISSUE TITLE
Contact History unavailable

### ISSUE THREAD

**Issue by Chaday** [SenitCorp/bugtracker#122]
Contact History will not come up. Will show empty with Retry button.

**Comment by jovi959** [comment]
Is this a consistent problem?

**Comment by jovi959** [comment]
also screenshoots would be helpful

**Comment by Chaday** [comment]
![nohistory](https://user-images.githubusercontent.com/31829711/46741775-5423cf00-cc6b-11e8-8da5-8ae5943c9f11.png)
