### ISSUE TITLE
Activity Screen Issues

### ISSUE THREAD

**Issue by Chaday** [SenitCorp/bugtracker#124]
When i send a request in the app sometimes it shows in my activity feed as Requested sometimes it shows as Requesting.

**Comment by jovi959** [comment]
Could you provide us with screenshots highlighting this.

**Comment by Chaday** [comment]
![screenshot_20181010-081236](https://user-images.githubusercontent.com/31829711/46741688-2fc7f280-cc6b-11e8-8a64-41cbc3aafe57.png)
