### ISSUE TITLE
Google Authenticator Code Screen does not match current design.

### ISSUE THREAD

**Issue by qatester1234** [SenitCorp/bugtracker#135]
Google Authenticator Code Screen does not match current design.  Please see the current design below.
The input field format is different , the screen icon is different , the screen / page title is different.

![image](https://user-images.githubusercontent.com/42078536/47105880-2f9f9800-d213-11e8-92b9-f9d666e0c1c1.png)

**Comment by qatester1234** [comment]
This is a picture of the old screen.
![screenshot_20181017-132445 1](https://user-images.githubusercontent.com/42078536/47108381-8019f400-d219-11e8-9421-31bac10a84ea.png)

**Comment by Ibar000** [comment]
@Chaday could you please send an PNG image of the Google Authenticator icon from the design? Thanks

**Comment by jovi959** [comment]
iOS completed

**Comment by Chaday** [comment]
Sur3

**Comment by Ibar000** [comment]
iOS and Android completed
