### ISSUE TITLE
ios app restart forgets my country code

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#142]
so trying to sync my ios app just kicked me you and i have to sign in again.  problem is that i am now set to Spain as my country code when the app should know i am signed up uisng a Jamaica number - even if i have to enter my phone number again ?

these basic barriers to entry for using the app are really not acceptable - we need to make sign up and sign in as EASY as possible as if you cant get past them then we loos you as a user

**Comment by jovi959** [comment]
iOS completed now storing country details on registration and login. if you are signout for some reason it will always remember the last country you used to sign up or login
