### ISSUE TITLE
mobile app sync taking forever users not getting transaction data ios

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#145]
So having issues with sync and iOS client

1. Sent $20 usd to Robert
2. Transaction Completed
3. Activity feed and balance were instantly update when i was returned (didnt see any rabits)

PERFECT

then IMMEDIATELY

1. I Sent $20 to Sam
2. Transaction completed
3. balance was not updated and transaction was not in my activity feed when i was returned
4. waited 5 seconds nothing
5. manually synced the activity feed by dragging down
6. hung syncing forever - like 3 seocnds
7. after 3 seconds my balance changed
8. after 5 seconds sams transaction turned up

so sync took over 5+ seconds which is a eternity

not sure if this is because i did 2 transaction back to back ?

**Comment by jahshaka** [comment]
relate to bug 136 possibly

https://github.com/SenitCorp/bugtracker/issues/136

**Comment by jovi959** [comment]
iOS completed. On a success transaction data is push to activity list on immediately.

**Comment by jahshaka** [comment]
is this still on going
