### ISSUE TITLE
Android sms codes not being auto processed any more at sign up

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#148]
autodetection needs to work properly - and be immediatly used once detected

i notice that on IOS this is now possible as well as my ios devices tell me the code however dont act on it

**Comment by jovi959** [comment]
Ok i will looking to it seems it a new feature in iOS 12

**Comment by tajwane** [comment]
on Android did you allow permissions when prompted as SMS auto detection only works if the SMS permission is allowed by the user

**Comment by jayrulez** [comment]
Can we get some more testing on this? It works for me. @SamuelFolkes @jahshaka can you confirm that this is fixed as it was observed only on your phones. Also, ensure that you allowed the SMS permission for the app.

**Comment by SamuelFolkes** [comment]
Fixed for me.
