### ISSUE TITLE
add all african currencies to currency manager

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#149]
currently we dont have African countries and their currencies listed

currency List needs to be alphabetized its random –ok.
But list major currencies at the top and then divider and rest –ok

**Comment by jahshaka** [comment]
has this been done already ?

**Comment by jayrulez** [comment]
No.

This will be done Today.
https://en.wikipedia.org/wiki/List_of_currencies_in_Africa

**Comment by SamuelFolkes** [comment]
done
