### ISSUE TITLE
Activity - hidden amount setting needs tweaking

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#157]
a.	Activity - hidden amount setting –ok.
i.	get rid of HIDDEN text when active
ii.	insrtead show larger (sx height) currency buttons
iii.	press the currency button to see amount, press again to hide and auto hide

**Comment by jovi959** [comment]
So i understand when the setting is on you can press the button and it shows the balance if you tap it again it hides it and after some time if you leave it on it will go back to hidden (which are all currently implemented), but just to clarify does "active" me when you press the button, and at what point do we show taller buttons all the time or only when "active"

**Comment by jahshaka** [comment]
we can leave it as it is for now as we have a new design coming and may get rid of the currency boxes in the header

Instead of 

HIDDEN 

just say

Your Balance

**Comment by jovi959** [comment]
Android update completed tap once show tap again hide and hide balance after some time of being visible .
