### ISSUE TITLE
fix notes to be inline

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#16]
get rid of the notes box and add notes inline with the other items on the receipts... i had sent over a image of how this should look. means also no scrolling behind notes etc

![image](https://user-images.githubusercontent.com/6324793/43375277-517ece52-93b4-11e8-9aca-8031211eafe1.png)

**Comment by jovi959** [comment]
iOS added

**Comment by jovi959** [comment]
Android added
