### ISSUE TITLE
currency conversion not working in calculator on android

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#161]
when on the calculator, on the first page of send and receive, the currency conversion is not working when you switch between currencies 

this works on ios...

**Comment by jahshaka** [comment]
also, while this works on iOS, the formatting is not correct ie we get 6325.5 usd instead of $6,325.50 when swapping from 1 btc to usd... important to get this working right

**Comment by jovi959** [comment]
ios completed
