### ISSUE TITLE
Format amounts consistently across the app

### ISSUE THREAD

**Issue by jayrulez** [SenitCorp/bugtracker#173]
Find all places in the app where currency amounts are displayed/inputted and pass them through a consistent formatter.

The formatter ideally should take the amount and the currency information (precision, display format).

You will probably need a constant list of all the currency templates.
We should be able to provide this from the server as the functionality is already there, it is just not being used right now.

![img_2511](https://user-images.githubusercontent.com/78807/48172062-5ca01180-e2cc-11e8-8a09-af7ea298d807.JPG)
![amount entry](https://user-images.githubusercontent.com/78807/48172070-6164c580-e2cc-11e8-866c-8ef3c15ea16d.jpg)

**Comment by jovi959** [comment]
iOS COmpleted
