### ISSUE TITLE
Not able to conduct transactions in other Currencies other than BTC.

### ISSUE THREAD

**Issue by GinaM876** [SenitCorp/bugtracker#177]
![screenshot_20190114-084912](https://user-images.githubusercontent.com/43448432/51277323-420da700-19a5-11e9-9b7d-c25aa5527458.png)
![screenshot_20190114-084854](https://user-images.githubusercontent.com/43448432/51277331-49cd4b80-19a5-11e9-9dbf-f3724891bbdf.png)

Trying to send in JMD & USD but I'm getting the error message @SamuelFolkes .

**Comment by jayrulez** [comment]
@Ibar000 can you check out what's happening here?

**Comment by Ibar000** [comment]
Fixed
