### ISSUE TITLE
zero balance after receiving funds

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#18]
sent a user $5 dollars of bitcoin and he still has zero balance ?

![image](https://user-images.githubusercontent.com/6324793/43375114-6c70183e-93b3-11e8-8860-5c999dba0f3b.png)

**Comment by jayrulez** [comment]
This should be fixed but we will need more testing to confirm that it doesn't happen again.

I will mark as closed for now.

We can re-open if the issue occurs again,
