### ISSUE TITLE
make sms invitations non editable...

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#19]
dont want to be a spam bot also need to make the bttons larger to match the rest of the app this dialog looks like a hack ?

![image](https://user-images.githubusercontent.com/6324793/43375143-9023ae1c-93b3-11e8-94c0-70de9dd9928b.png)

**Comment by jahshaka** [comment]
also please add url shorteners for the url of iOS and Andorid downlaods so the sms message isnt so crazy

ie links to app store and google play need to be

https://www.senit.com/get-senit-ios

https://www.senit.com/get-senit-android

**Comment by jovi959** [comment]
iOS field non editalbe
