### ISSUE TITLE
need to address rotating wallets in main account info page (QR code page)

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#20]
to add rotating wallets for security, so people cant look up your balance, users need a settings where thier master wallet is and all child wallets that have been created listed for transaprency

we suggested rotate 10 wallets until they use them up and add 1 for every 1 thats used... so FIFO

but we cant give out the master wallet in the account page !!! so if doing this is a lot of work then we need for every user to start 1 master and 1 linked wallet... with no rotation

**Comment by jayrulez** [comment]
This is fixed in code and will be available in the next server deployment.

The framework was already there for this.

The issue is that we were not marking wallet addresses as used when they are used.

This is being done now.
