### ISSUE TITLE
use new rounded buttons 

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#24]
need to ensure we are using new rounded buttons everywhere...  for eg they areunt used here

<img width="779" alt="screen shot 2018-07-30 at 4 55 42 am" src="https://user-images.githubusercontent.com/6324793/43375358-d5d32c8e-93b4-11e8-9ec8-e214a1a6aa56.png">

**Comment by jovi959** [comment]
Completed
