### ISSUE TITLE
when i log in app doesnt remember my country

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#28]
when i log out of the app and go to log back in the app still takes me to the list of countries  to choose my country even though 876 is in the phone numher field ? it needs to remeber my country as i can still override

want to make sure people never see that annoying lit of countries it kills the sign up sign in process

**Comment by Ibar000** [comment]
fixed

**Comment by tajwane** [comment]
Fixed on version 3.12
