### ISSUE TITLE
issues with phone number prefix

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#29]
when i enter my phone number sometimes it registers as 1876 not 1 876 ? the former doesnt show up as a registered number

**Comment by Ibar000** [comment]
Can you recall for which use case(s) in particular this issue was observed?

**Comment by jayrulez** [comment]
Which os is this?

**Comment by senit** [comment]
Ios

**Comment by jayrulez** [comment]
Closing as this issue cannot be reproduced. Re-open if you are able to reproduce it.
