### ISSUE TITLE
underline text on buttons on Startup screen

### ISSUE THREAD

**Issue by Ibar000** [SenitCorp/bugtracker#34]
the concern is that this may create a Web App look and feel to the application 

![image from ios](https://user-images.githubusercontent.com/22422309/43661479-105c2e0c-9728-11e8-85b0-24d33d533eae.jpg)

**Comment by Ibar000** [comment]
[Jovi]
Underline is a result of an iOS accessiblity feature enabled in user settings to help users identify buttons. This is located in Settings -> general -> accessibility -> button shapes.

**Comment by jovi959** [comment]
not a bug is a user setting
