### ISSUE TITLE
bitcoin balance showing up with way too many zeros

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#4]
bitcoin balances in activity main bar need to be rounded down to remove the zeros...

mayte has 0.25 btc it shows as 0.250000000 should just shows as 0.25

same goes for on receipt pages of bitcoin transactions... they also show up as 0.0100000000 should be 0.01

check for ios and android please

**Comment by jahshaka** [comment]
![image from ios 2](https://user-images.githubusercontent.com/6324793/43374575-abdfb6e4-93b0-11e8-9c65-f64aa9485ea3.jpg)

![image from ios 1](https://user-images.githubusercontent.com/6324793/43374579-b1c38b08-93b0-11e8-854d-6f15c8ae2622.jpg)

**Comment by jovi959** [comment]
iOS completed
