### ISSUE TITLE
no available carriers for mobile top-up of numbers belonging to particular countries

### ISSUE THREAD

**Issue by Ibar000** [SenitCorp/bugtracker#43]
[Karsten]
No topup for Uk numbers ??

![image from ios 6](https://user-images.githubusercontent.com/22422309/43665076-a25a311c-9734-11e8-83c3-bbf415f7bef0.jpg)

**Comment by jovi959** [comment]
iOS fix bug caused bitrefill api returning of inconsistent data
{
			"value": "10",
			"eurPrice": 11.67,
			"satoshiPrice": 182400,
			"usdPrice": 13.5,
			"userPrice": 182400
}
value is string here
{
			"value": 1000,
			"eurPrice": 6.8,
			"satoshiPrice": 106000,
			"usdPrice": 7.87,
			"userPrice": 106000
}
 whiles it not here
