### ISSUE TITLE
app displays "insufficient balance" error for p2p transaction that is within the account balance limit

### ISSUE THREAD

**Issue by Ibar000** [SenitCorp/bugtracker#48]

**Comment by tajwane** [comment]
This may occur whenever you are trying to send an amount below the threshold limit. example(trying to send 0.01 USD). Will look into displaying a better error message than "Insufficient balance"

**Comment by jayrulez** [comment]
We need to come up with some rules for this:

We need to establish a minimum amount that we allow to be sent so we can check and display a proper error message.

This can happen if we are sending lower that the network allows or if the amount being sent exceeds the account balance + mining fee.

**Comment by rox117** [comment]
Appropriate error message now returned when amount being sent is below 100 JMD

**Comment by jahshaka** [comment]
why below 100 jmd = this error should be calculated in bitcoin since its our store ofr vlaue -  and then converted to the currency the persona is using

**Comment by jahshaka** [comment]
also this should be a standard error if total sent + fees are more than total they have no ?  npthing special about this error really is there other than we need it for any case where total sent + fees is greater than total in wallet regardless

can we display these errors on a pop up dialog box on the confirm and send page  instead of after the transaction has processed

**Comment by jahshaka** [comment]
what is the error exactly ? should be something like....

You have insufficient funds to complete this transaction after the transaction fees are applied.

**Comment by rox117** [comment]
> why below 100 jmd = this error should be calculated in bitcoin since its our store ofr vlaue - and then converted to the currency the persona is using

It is calculated in bitcoin, it is equivalent to 100 jmd worth of bitcoin currently, where it is configurable and can be changed if necessary. There exists another error if total fees + amount is less than the current balance that is already displayed in the app. When processing transactions there is a variable  minimum limit that bitgo allows. An error would be thrown by bitgo when a user sends below this limit. This measure was put in place to prevent that from happening.
