### ISSUE TITLE
Currency Display Issues  

### ISSUE THREAD

**Issue by qatester1234** [SenitCorp/bugtracker#52]
We need to revise the currency displays between Send and Request screen;  prior to Confirm and Pay.
 [Dane]
Getting "Insufficient balance" when trying to send amount in a switched currency, and the amount is larger in face value than the reference currency.

**Comment by tajwane** [comment]
Not understanding the problem here, are you saying whenever you try to send money you get an error saying "insufficient balance" even thou you have sufficient balance. Please to clarify whats the issue you have when trying to send or request funds

**Comment by qatester1234** [comment]
When performing a Send Request , the Send Currency changes to the Wallet Balance Currency; which is not correct.
