### ISSUE TITLE
Tutorial Dialog Window requesting Existing Photo ID and EMail Address

### ISSUE THREAD

**Issue by qatester1234** [SenitCorp/bugtracker#53]
each time I sign in, MPago Tutorial requesting that I should ADD Photo ID and Email Address when they already exist.

![screenshot_20180803-181953](https://user-images.githubusercontent.com/22422309/43669646-235861ac-974a-11e8-943a-8ba9c8f4f708.png)

**Comment by tajwane** [comment]
Issue fixed and will be available in version 3.05 Android.
