### ISSUE TITLE
send bitcoin receipt not matching send user bitcoin receipt

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#6]
the recept i see when i send bitcoin externally needs to match the one i see when i send a user (p2p) bitcoin 

this is the old style

![image](https://user-images.githubusercontent.com/6324793/43375291-6d33f10e-93b4-11e8-90ce-888100a900dc.png)

this is the new style

![image](https://user-images.githubusercontent.com/6324793/43375298-75e2f5b6-93b4-11e8-97f0-f757ce2a3fe8.png)

**Comment by jovi959** [comment]
iOS change over to p2p designs

**Comment by jayrulez** [comment]
Is this issue for iOS only?
