### ISSUE TITLE
Insufficient balance shown when trying to send

### ISSUE THREAD

**Issue by Chaday** [SenitCorp/bugtracker#78]
Insufficient balance message was displayed in a small grey box on screen even though in my wallet their is a lot more bitcoin than i am trying to send.

**Comment by Ibar000** [comment]
Hey Chantel,
Could you reproduce a screenshot of this issue (if possible) and place it below your description? 
Also, supplying specific data, such as, your balance at the time and the amount your are sending (in what currency) would also help to pin point the cause.

Thanks

**Comment by Chaday** [comment]
Alright will do this and send.
