### ISSUE TITLE
Currency toggle on send screen is not two way bounded.

### ISSUE THREAD

**Issue by jayrulez** [SenitCorp/bugtracker#83]
If I toggle the send currency the currency of the account balance also changes.

When I toggle the account balance currency the send currency does not change.

Not sure if the is the desired behaviour but it seems a bit strange.

**Comment by jayrulez** [comment]
@senit comment?

**Comment by Ibar000** [comment]
Robert, 
I believe this behaviour to be by design.  Jovi reports that the iOS client behaves the same way.
Regards

**Comment by Ibar000** [comment]
fixed on Android
