### ISSUE TITLE
Tutorials design issues

### ISSUE THREAD

**Issue by DariaFabro** [SenitCorp/bugtracker#84]
1. All tutorial windows should have a SHADE of some sort so that they send out from the app - right now they totally blend in and it looks like the app has an issue... Maybe also have the background of slightly different color - will also help.
Also, the first window should specify that we are going through icons at the bottom bar - as a user I have no idea what are you talking about in the next slides...
2. The 2nd tutorial window - it should be titled QR Code (as that's what the icon looks like) and not Wallet Address. 
It also has bad English, it should say something like that: "Find, share and copy your wallet address (QR code) here. Also scan other QR codes."
3. The 3rd tutorial window again has bad English. It should say: "Keep track of your financial contacts and invite new contacts to Mpago."
4. The 4th tutorial window - it should be titled Messages / Activity (as that's what it says in the app and this icon switches between Messages and Activity) and not Chat. 
Again has bad English. It should say something like: "Message your contacts here using our fast and simple chat. Or go back HOME".
5. Next icon is actually PROFILE so next slide should be PROFILE and not APP STORE. Again, name needs to be adjusted. 
6. Last slide - the dot is not visible for this one in the bottom line - looks terrible. I would also change the text here as it is not very clear. I would say something like: "Chose from thousands of apps to take advantage of other Mpago payment services."

**Comment by Ibar000** [comment]
completed on Android
