### ISSUE TITLE
country and area code incorrect

### ISSUE THREAD

**Issue by rox117** [SenitCorp/bugtracker#85]
After selecting a country code and area code,upon closing and reopening the app an incorrect country code is displayed.

![screenshot_20180918-180342](https://user-images.githubusercontent.com/8076406/45721371-7004eb00-bb6d-11e8-951b-4feea812d897.png)

**Comment by Ibar000** [comment]
fixed

**Comment by rox117** [comment]
howd you manage to reproduce
